# TCL File Generated by Component Editor 21.1
# Fri May 10 12:22:34 EDT 2024
# DO NOT MODIFY


# 
# freq_detect "Freq Detect" v1.0
#  2024.05.10.12:22:34
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module freq_detect
# 
set_module_property DESCRIPTION ""
set_module_property NAME freq_detect
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Freq Detect"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL freqdetect
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file freqdetect.sv SYSTEM_VERILOG PATH freqdetect.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point fdc
# 
add_interface fdc conduit end
set_interface_property fdc associatedClock clock
set_interface_property fdc associatedReset ""
set_interface_property fdc ENABLED true
set_interface_property fdc EXPORT_OF ""
set_interface_property fdc PORT_NAME_MAP ""
set_interface_property fdc CMSIS_SVD_VARIABLES ""
set_interface_property fdc SVD_ADDRESS_GROUP ""

add_interface_port fdc detectdone fdc_detectdone Output 1
add_interface_port fdc fftdone fdc_fftdone Input 1
add_interface_port fdc maxbin fdc_maxbin Output 10
add_interface_port fdc ramaddr fdc_ramaddr Output 10
add_interface_port fdc ramq fdc_ramq Input 28

