# TCL File Generated by Component Editor 21.1
# Fri May 10 13:14:06 EDT 2024
# DO NOT MODIFY


# 
# weightblock "Weight Block" v1.0
#  2024.05.10.13:14:06
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module weightblock
# 
set_module_property DESCRIPTION ""
set_module_property NAME weightblock
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Weight Block"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL weightblock
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file compmult.v VERILOG PATH compmult.v
add_fileset_file realmult.v VERILOG PATH realmult.v
add_fileset_file delay_ROM.v VERILOG PATH delay_ROM.v
add_fileset_file angdisplay.sv SYSTEM_VERILOG PATH angdisplay.sv
add_fileset_file weightblock.sv SYSTEM_VERILOG PATH weightblock.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point wb
# 
add_interface wb conduit end
set_interface_property wb associatedClock clock
set_interface_property wb associatedReset ""
set_interface_property wb ENABLED true
set_interface_property wb EXPORT_OF ""
set_interface_property wb PORT_NAME_MAP ""
set_interface_property wb CMSIS_SVD_VARIABLES ""
set_interface_property wb SVD_ADDRESS_GROUP ""

add_interface_port wb disp0 wb_disp0 Output 7
add_interface_port wb disp1 wb_disp1 Output 7
add_interface_port wb bnum wb_bnum Output 6
add_interface_port wb detectdone wb_detectdone Input 1
add_interface_port wb disp2 wb_disp2 Output 7
add_interface_port wb doa wb_doa Output 8
add_interface_port wb done wb_done Output 1
add_interface_port wb maxbin wb_maxbin Input 10
add_interface_port wb ramq1 wb_ramq1 Input 28
add_interface_port wb ramq2 wb_ramq2 Input 28
add_interface_port wb ramq3 wb_ramq3 Input 28
add_interface_port wb ramq4 wb_ramq4 Input 28
add_interface_port wb rdaddr2 wb_rdaddr2 Output 10
add_interface_port wb rdaddr3 wb_rdaddr3 Output 10
add_interface_port wb rdaddr4 wb_rdaddr4 Output 10

